# Site settings
title: icbcbicc's Blog
header-img: img/home-bg.jpg
email: icbcbicc@gmail.com
copyright_name: icbcbicc's Blog
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
encoding: utf-8
url: "http://icbcbicc.github.io"
#twitter_username: 
github_username:  icbcbicc
#facebook_username:  IronSummitMedia
email_username:  icbcbicc@hotmail.com
port: 4001
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
